# Generated by Django 3.2.16 on 2022-11-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("collector_number", models.CharField(max_length=10)),
                ("edition", models.CharField(max_length=10)),
                (
                    "image_png",
                    models.ImageField(blank=True, null=True, upload_to="cards_images"),
                ),
                ("image_status", models.CharField(default="", max_length=10)),
                ("png_url", models.URLField(default="")),
                ("image_size", models.IntegerField(default=0)),
                ("frame", models.CharField(default="", max_length=10)),
                ("type_line", models.CharField(default="", max_length=30)),
                ("lang", models.CharField(default="", max_length=10)),
                ("full_art", models.BooleanField(default=False)),
            ],
        ),
    ]
