# Generated by Django 3.2.16 on 2022-11-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
