# Generated by Django 3.2.16 on 2022-11-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_card_image_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="type_line",
            field=models.CharField(default="", max_length=200),
        ),
    ]
