# Generated by Django 3.2.16 on 2022-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_card_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="png_bluriness",
            field=models.FloatField(default=0.0),
        ),
    ]
