# Generated by Django 3.2.16 on 2022-11-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221107_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='oracle_id',
        ),
        migrations.AddField(
            model_name='card',
            name='oracle_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='face',
            name='oracle_text',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
