# Generated by Django 3.2.16 on 2022-11-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_card_png_bluriness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards_images')),
                ('extension', models.CharField(default='', max_length=10)),
                ('url', models.URLField(default='')),
                ('bluriness', models.FloatField(default=0.0)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='image_png',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='card',
            name='png_bluriness',
        ),
        migrations.RemoveField(
            model_name='card',
            name='png_url',
        ),
    ]
