# Generated by Django 3.2.16 on 2022-11-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221107_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='oracle_text',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
