# Generated by Django 4.1.3 on 2022-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_face_oracle_text'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('scryfall_id',), name='unique_scryfall_id'),
        ),
    ]
