# Generated by Django 3.2.16 on 2022-11-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20221106_2008"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.card",
            ),
        ),
    ]
