# Generated by Django 4.1.3 on 2022-11-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_face_unique_face_card'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='face',
            name='unique_face_card',
        ),
    ]
