# Generated by Django 4.2.30 on 2026-05-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_face_unique_face_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.CharField(default='', max_length=50),
        ),
    ]
