# Generated by Django 4.2.30 on 2026-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_card_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=500),
        ),
    ]
