# Generated by Django 4.2.30 on 2026-05-26 20:35

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_card_layout'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='face',
            index=models.Index(django.db.models.functions.text.Upper('name'), name='face_name_upper_idx'),
        ),
    ]
