# Generated by Django 4.2.30 on 2026-05-29 08:21

from django.db import migrations, models


def populate_face_index(apps, schema_editor):
    Face = apps.get_model('api', 'Face')
    card_ids = Face.objects.values_list('card_id', flat=True).distinct()
    for card_id in card_ids:
        for i, face in enumerate(Face.objects.filter(card_id=card_id).order_by('id')):
            face.face_index = i
            face.save(update_fields=['face_index'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_face_face_name_upper_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='face_index',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(populate_face_index, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='face',
            constraint=models.UniqueConstraint(fields=('card', 'face_index'), name='unique_face_card_index'),
        ),
    ]
