# Generated by Django 6.0.5 on 2026-06-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='card_oracle_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='card_image_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='face',
            name='face_name_upper_idx',
        ),
        migrations.RemoveIndex(
            model_name='face',
            name='face_side_idx',
        ),
    ]
